#!/usr/bin/env python3
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
TRANSCRIPT = ROOT / 'site' / 'cli-transcript.txt'
RECEIPT = 'receipts/live-band-demo-20260618T185330Z.json'

COMMANDS = [
    {
        'display': f'python scripts/receipt_timeline.py {RECEIPT}',
        'argv': [sys.executable, 'scripts/receipt_timeline.py', RECEIPT],
    },
    {
        'display': f'PYTHONPATH=src python -m roomkey.cli verify {RECEIPT}',
        'argv': [sys.executable, '-m', 'roomkey.cli', 'verify', RECEIPT],
        'env': {'PYTHONPATH': 'src'},
    },
    {
        'display': f'python scripts/judge_proof.py {RECEIPT}',
        'argv': [sys.executable, 'scripts/judge_proof.py', RECEIPT],
    },
    {
        'display': 'python scripts/browser_verifier_contract_check.py --root .',
        'argv': [sys.executable, 'scripts/browser_verifier_contract_check.py', '--root', '.'],
    },
]


def run_command(spec: dict[str, Any]) -> str:
    env = os.environ.copy()
    for key, value in dict(spec.get('env', {})).items():
        env[str(key)] = str(value)
    proc = subprocess.run(
        [str(part) for part in spec['argv']],
        cwd=ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    block = [f'$ {spec["display"]}']
    if proc.stdout:
        block.append(proc.stdout.rstrip())
    if proc.stderr:
        block.append('[stderr]')
        block.append(proc.stderr.rstrip())
    block.append(f'exit_code={proc.returncode}')
    if proc.returncode != 0:
        raise RuntimeError('\n'.join(block))
    return '\n'.join(block)


def build_transcript() -> str:
    blocks = [
        '# RoomKey ScopeGate real CLI transcript',
        '# Generated by scripts/build_cli_transcript.py from committed receipt/proof files.',
        '# No browser button output is fabricated here; every block below is command stdout.',
        '',
    ]
    for spec in COMMANDS:
        blocks.append(run_command(spec))
        blocks.append('')
    return '\n'.join(blocks).rstrip() + '\n'


def main() -> int:
    transcript = build_transcript()
    TRANSCRIPT.write_text(transcript, encoding='utf-8')
    print(f'wrote {TRANSCRIPT.relative_to(ROOT)} bytes={len(transcript.encode("utf-8"))}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
