from __future__ import annotations

from typing import Protocol

from roomkey.models import AgentRole, GateEvent


class BandRoomClient(Protocol):
    async def send_message(self, room_id: str, mention: AgentRole | str, text: str) -> str: ...
    async def send_event(self, room_id: str, event: GateEvent) -> str: ...
    async def lookup_peers(self, query: str | None = None) -> list[dict]: ...
    async def add_participant(self, room_id: str, agent: AgentRole | str) -> str: ...
    async def remove_participant(self, room_id: str, agent: AgentRole | str) -> str: ...
    async def export_transcript(self, room_id: str) -> dict: ...
